### ISSUE TITLE
link not readable in termux 

### ISSUE THREAD

**Issue by Hussain4div** [htr-tech/nexphisher#1]
hi I try the tool on pc it run great
but I tryed it in my phone 📱 it runs 
but the generator link not visible I tried to highlight it but still not visible. 

![Screenshot_20200416-155716_Termux](https://user-images.githubusercontent.com/63794322/79460331-56ec4680-7ffd-11ea-874f-f45b23d1d4d8.jpg)

great work 
good luck

**Comment by htr-tech** [comment]
@Hussain4div  Bro first turn on your hotspot & try . But the serveo wont work .

**Comment by karthi24061** [comment]
I have the same issues... I'm not getting that link while clicking ngrok

**Comment by htr-tech** [comment]
@karthi24061 Bro first turn on your hotspot & try

**Comment by CorruptedgriphtV** [comment]
Hi, i tried on hospot and nothing happens, i tried to change my ip using a VPN and it still in the same issue, do you can help me I'll appreciate that

**Comment by htr-tech** [comment]
Then forward manually

**Comment by CorruptedgriphtV** [comment]
> Then forward manually

How I can do that (Consider novice users)

**Comment by akshaygrandhi** [comment]
Getting an error while setting up the environment.
mv: cannot stat 'loclx': No such file or diectory
chmod: cannot access '.htr/loclx': No such file or directory.
could you please help me with this

**Comment by htr-tech** [comment]
> Getting an error while setting up the environment.
> mv: cannot stat 'loclx': No such file or diectory
> chmod: cannot access '.htr/loclx': No such file or directory.
> could you please help me with this

remove the dir & reclone & put the commands correctly 

apt update
apt install git -y
git clone git://github.com/htr-tech/nexphisher.git
cd nexphisher

> SETUP [TERMUX] : bash tmux_setup
> SETUP LINUX  : bash setup

> Run : bash nexphisher

**Comment by akshaygrandhi** [comment]
Did that but getting the same error.

**Comment by htr-tech** [comment]
> Did that but getting the same error.

if you are root then try with sudo

**Comment by akshaygrandhi** [comment]
No I am not the root user

**Comment by htr-tech** [comment]
> No I am not the root user

you use what ? termux or linux distro ??

**Comment by akshaygrandhi** [comment]
Termux

**Comment by htr-tech** [comment]
@akshaygrandhi  contact here https://www.instagram.com/tahmid.rayat/

**Comment by akshaygrandhi** [comment]
Sure

**Comment by nahid444620** [comment]
Link Why not open

**Comment by weewuxian** [comment]
Link show nahi ho raha hai bro 7to8 times try kar liya

**Comment by weewuxian** [comment]
> hi I try the tool on pc it run great
> but I tryed it in my phone 📱 it runs 
> but the generator link not visible I tried to highlight it but still not visible. 
> 
> ![Screenshot_20200416-155716_Termux](https://user-images.githubusercontent.com/63794322/79460331-56ec4680-7ffd-11ea-874f-f45b23d1d4d8.jpg)
> 
> great work 
> good luck 
> 

Same problem mere sath bhi hai

**Comment by weewuxian** [comment]
What i do

**Comment by Lakshay1622** [comment]
I'm getting same problem from nexphisher and even zphisher...ngrok link is blank...and localhost link showing "something is wrong" after sending someone. 
Update is ASAP bro.

**Comment by TheRoyalOne2021** [comment]
the way to fix this is by typing ./ngrok http 5555 in a seperate terminal then setup nexphisher like usual with what you want and the link won't show in the nexphisher window but instead,once it's setup you click one of the ngrok links in the seperate terminal,and like a charm it takes you to the password hacking webpage you setup,and you can even use an https or http version of the link to make it more believable

**Comment by Kaah23** [comment]
Eu fiz no termux, mas quando termina não aparece o link, alguem me ajuda pfv

**Comment by avdhutdixit** [comment]
Generated link is not working in victim's device

**Comment by braiden656** [comment]
Y'all should turn on your hotspots for the link to show up.

**Comment by asdfghjkjhgfdsadfgh** [comment]
link is showing not reachable in victims device

**Comment by asdfghjkjhgfdsadfgh** [comment]
help me

**Comment by asdfghjkjhgfdsadfgh** [comment]
the link is http://127.0.0.1:5555/

**Comment by asdfghjkjhgfdsadfgh** [comment]
http://127.0.0.1:5555/ is not working ...... why

**Comment by FKKHAN302** [comment]
Command
