### ISSUE TITLE
Packages are not Installed ! type bash setup

### ISSUE THREAD

**Issue by Terryje-y** [htr-tech/nexphisher#107]

**Comment by xenonxander** [comment]
Same problem here

**Comment by htr-tech** [comment]
if you are using termux then type `bash tmux_setup` first then type `bash nexphisher` to run the tool

and if you are using any other distribution then type `bash setup` first then type `bash nexphisher` to run the tool

**Comment by xenonxander** [comment]
> if you are using termux then type `bash tmux_setup` first then type `bash nexphisher` to run the tool
> 
> and if you are using any other distribution then type `bash setup` & then type `bash nexphisher` to run the tool

![Screenshot_20210706-175701_Chrome](https://user-images.githubusercontent.com/76180175/124581408-ab3e4900-de83-11eb-96e6-c73ca534d1de.jpg)


It became like this. The Facebook login page became white background and it's obviously fake. What is the solution for this? Please help..

Thank you Sir

**Comment by anujsahoo13** [comment]
Ok sir

**Comment by xenonxander** [comment]
> > if you are using termux then type `bash tmux_setup` first then type `bash nexphisher` to run the tool
> > and if you are using any other distribution then type `bash setup` & then type `bash nexphisher` to run the tool
> 
> ![Screenshot_20210706-175701_Chrome](https://user-images.githubusercontent.com/76180175/124581408-ab3e4900-de83-11eb-96e6-c73ca534d1de.jpg)
> 
> It became like this. The Facebook login page became white background and it's obviously fake. What is the solution for this? Please help..
> 
> Thank you Sir

I can't resolve it until now. Please help

**Comment by htr-tech** [comment]
> > > if you are using termux then type `bash tmux_setup` first then type `bash nexphisher` to run the tool
> > > and if you are using any other distribution then type `bash setup` & then type `bash nexphisher` to run the tool
> > 
> > 
> > ![Screenshot_20210706-175701_Chrome](https://user-images.githubusercontent.com/76180175/124581408-ab3e4900-de83-11eb-96e6-c73ca534d1de.jpg)
> > It became like this. The Facebook login page became white background and it's obviously fake. What is the solution for this? Please help..
> > Thank you Sir
> 
> I can't resolve it until now. Please help

page updated ,,, 
remove the tool & clone again

**Comment by braiden656** [comment]
Thanks sir...i was using termux but it worked Thank Sir
