### ISSUE TITLE
I don't get a link

### ISSUE THREAD

**Issue by NovaBG03** [htr-tech/nexphisher#118]
![image](https://user-images.githubusercontent.com/43469098/130333378-2125ff09-49f9-4bac-a28e-48cf226c1914.png)

**Comment by NovaBG03** [comment]
Have tried changing the token - didn't work, then tried this https://replit.com/repls/GaseousFormalAttributes - didn't work as well

**Comment by mohamed5600** [comment]
I am also facing the same problem, but I can face it by copying the link before starting the page
![Screenshot_2021-08-22-15-30-13](https://user-images.githubusercontent.com/89344376/130357095-408b31a8-9800-4483-8962-30e2f38023da.png)
![Screenshot_2021-08-22-15-30-25](https://user-images.githubusercontent.com/89344376/130357106-5cc22453-a482-41bd-9935-3312f8aa337a.png)

**Comment by mservini1** [comment]
Any fixes for no links?

**Comment by FuriousLeech** [comment]
> Any fixes for no links?

so basically open a ngrok with the same port that the program uses, in this case its 5555. ./ngrok http 5555. do this before running nexphiser, THEN, when it says send to victim, send them the ngrok url that you got before. this worked 100% for me, and will solve ANY phisher not giving you the ngrok url. hope this made sense

**Comment by NovaBG03** [comment]
Yes, I found that that worked for me

**Comment by killerkalai** [comment]
![Screenshot at 2022-08-09 11-29-40](https://user-images.githubusercontent.com/110893108/183603332-eaf39a1d-90d1-42cd-9ce7-f32ef8b9bee1.png)
![Screenshot at 2022-08-09 11-29-40](https://user-images.githubusercontent.com/110893108/183603415-cf695600-d799-4b9b-9aee-927f41d1a2b0.png
please solve this error. there is no victim link please say solution
step by step procuder
