### ISSUE TITLE
 [~] Send the link to victim : https://1ca5701512e2.ngrok.io    [~] Waiting for Login Info, Ctrl + C to exit.  nexphisher: line 437:  3827 Segmentation fault      php -S 127.0.0.1:5555 > /dev/null 2>&1

### ISSUE THREAD

**Issue by net-war** [htr-tech/nexphisher#12]
Hey there, so i installed ngrok, pasted my authtoken and set http port to 80

then i start nexphisher, i go to Instagram, i select Blue Badge Option
it asks me to select port forwarding option, i chose ngrok, 
i send link to victim, they click on a windows or linux machine, no matter, they get Bad Gateway error IG login screen never opens.

On the nexphisher window.. i get this error:
 [~] Send the link to victim : https://1ca5701512e2.ngrok.io 

 [~] Waiting for Login Info, Ctrl + C to exit.

nexphisher: line 437:  3827 Segmentation fault      php -S 127.0.0.1:5555 > /dev/null 2>&1

please help!

**Comment by htr-tech** [comment]
#13

**Comment by olihackerz** [comment]
Do you have an ngrok account because you need that.

**Comment by Terminal-XX** [comment]
I have a problem with the link in nexphisher, I don't see the link, help me please

**Comment by thebestech** [comment]
I can't found this link 
Send this link to the Victim: 
help me

**Comment by LOVE143YOU** [comment]
i didn't get any link
help me
