### ISSUE TITLE
Empty link to the victim

### ISSUE THREAD

**Issue by rickycorral** [htr-tech/nexphisher#16]
Hi - I got an empty field using any of the Port Forwarding Options (5). Any solutions? Thank you!

 _  _ ___ _   _    ___  _  _ ___ ___ _  _ ___  ___
 |\ | |__  \_/    |___] |__|  |  |__ |__| |__ |__/
 | \| |__ _/ \_   |    _|  | _|_ ___||  |_|__ | \_ [V 1.0]

     Advanced Phishing Tool with 30+ Templates

    [ BY : https://github.com/htr-tech ]

 [~] Send the link to victim :

 [~] Waiting for Login Info, Ctrl + C to exit.

**Comment by htr-tech** [comment]
turn on hotspot & try again
