### ISSUE TITLE
No link to send

### ISSUE THREAD

**Issue by dienn03** [htr-tech/nexphisher#19]
When i want to get a link with ngrok i dont get a link for the victim
![Screenshot_20200715-213248_Termux](https://user-images.githubusercontent.com/66322268/87587764-d06e0080-c6e2-11ea-9e17-fe8841b0d33f.jpg)

**Comment by htr-tech** [comment]
turn on device hotspot & try again . i prefer ngrok or localxpose

**Comment by dienn03** [comment]
It works, thanks!
