### ISSUE TITLE
Caaaan weeee gettt it to verfiy the entered passswords  ?

### ISSUE THREAD

**Issue by minanagehsalalma** [htr-tech/nexphisher#2]
Huuuuh ?

**Comment by htr-tech** [comment]
ya

**Comment by minanagehsalalma** [comment]
@htr-tech  so are you going to add it ? 

Or its already there ??!

**Comment by PapitaRanciaUwU** [comment]
![image](https://user-images.githubusercontent.com/69615733/90092834-a3b40580-dcef-11ea-846e-a33f5623c770.png)

**Comment by PapitaRanciaUwU** [comment]
![image](https://user-images.githubusercontent.com/69615733/90092849-b4fd1200-dcef-11ea-82bf-f2adcc1d0b01.png)

**Comment by PapitaRanciaUwU** [comment]
![image](https://user-images.githubusercontent.com/69615733/90092856-bf1f1080-dcef-11ea-9489-65a5e048f01a.png)

**Comment by PapitaRanciaUwU** [comment]
![image](https://user-images.githubusercontent.com/69615733/90092874-cb0ad280-dcef-11ea-9c9b-d046e80ff53d.png)

**Comment by PapitaRanciaUwU** [comment]
![image](https://user-images.githubusercontent.com/69615733/90092886-d3fba400-dcef-11ea-8833-a15c1fdbbbf2.png)

**Comment by PapitaRanciaUwU** [comment]
double click on login and the passwords appear.

**Comment by minanagehsalalma** [comment]
> double click on login and the passwords appear.

@PapitaRanciaUwU i don't want them to appear ... i want the script to auto check if they are correct or not .. if not ask the victim to type them again.

**Comment by htr-tech** [comment]
> > double click on login and the passwords appear.
> 
> @PapitaRanciaUwU i don't want them to appear ... i want the script to auto check if they are correct or not .. if not ask the victim to type them again.

make it yourself Bruh !! or wait till 2050 😆😆😆

**Comment by minanagehsalalma** [comment]
> make it yourself Bruh !! or wait till 2050 😆😆😆

@htr-tech no thanks there is tons of better alternatives.
