### ISSUE TITLE
Ngrok error link

### ISSUE THREAD

**Issue by DESTRO-ORIGIN-ONE** [htr-tech/nexphisher#23]
When using the ngrok service I do not get the link to send the victim, what solution can you give me please, thanks

**Comment by htr-tech** [comment]
turn on hotspot & try ngrok

**Comment by DESTRO-ORIGIN-ONE** [comment]
> activa el punto de acceso y prueba ngrok

With this tool you just press the ngrok option and it will supposedly activate itself but nothing comes out of any link.

**Comment by htr-tech** [comment]
turn on hotspot & try ngrok

**Comment by DESTRO-ORIGIN-ONE** [comment]
> activa el punto de acceso y prueba ngrok

What do you mean by what are you saying?

**Comment by PapitaRanciaUwU** [comment]
help me pls
