### ISSUE TITLE
Server timeout 5/6 min later

### ISSUE THREAD

**Issue by darklordreborn** [htr-tech/nexphisher#24]
server time out after 5/6 min later.
normally ngrok gives 8 hour for tunnel without Sign Up....
why it's not happened here????

কাজ খুব ভালো হইছে ভাই।।।।
local storage কে হোস্টিং বানিয়ে কিছু করা যায়?
যেমন KsWeb করে।।।।
Htdoc ফোল্ডারে পেজ রেখে localhost রান করলে প্রথমে লোকালি রান হয়।
এই Local Storage থেকে ফিসিং ক্যাচ করবে আর ngrok দিয়ে এক্সপোজ হবে।।।এমন টা করা যায়না ভাই?

ngrok দিয়ে পোর্ট ফরোয়ার্ড করলে ৮ ঘন্টা টাইম দেয়।
কিন্তু এখানে ৫/৬ মিনিট পরই ডিসকানেক্ট হয় যায়।।।।।

**Comment by htr-tech** [comment]
ngrok er auth token dilei kaj korbe
