### ISSUE TITLE
It's not showing any links

### ISSUE THREAD

**Issue by bruh882** [htr-tech/nexphisher#25]
the link I'm supposed to send isn't showing, what do you mean by "turn on hotspot and try again?" 

do I have to switch to cellular data and a mobile hotspot instead of wifi? or something else? i tried both and the link still didn't appear, even with hotspot

**Comment by hdhacking** [comment]
> hotspot
I have the same issue,pls helo.

**Comment by darklordreborn** [comment]
If link not generate then try to on hostpot....
That's mean if link not generate then nexphisher will not work using wifi.....
coz if your wifi is turned on, hostpot will not turn on.....u have to turn off wifi first ....
Then turn on mobile data...
then try to trun on hostpot.....
everyone know we can't share wifi data with hostpot.
But we can share mobile data with hostpot.....

Go to setting>turn off wifi>turn on mobile data>turn on hostpot >try to run nexphisher  
>Try to Expose Tunnel Using Ngrok

**Comment by PapitaRanciaUwU** [comment]
I cannot activate mobile data on my laptop, it is not in the configuration either, only wifi and hostpot 2.0

**Comment by htr-tech** [comment]
in laptop turn on hotspot & try

**Comment by akramxxx** [comment]
When i use serveo port forwarding, then given me empty link...My hotspot turn on ..

**Comment by htr-tech** [comment]
@akramxxx serveo is down turn on hotspot & use ngrok

**Comment by akramxxx** [comment]
I do it but don't work

**Comment by anshikkumartiwari** [comment]
have done everything you want me to do, still the link is not visible... it's just blank. Hotspot was turned on and forwarding port I choosed was ngrok

**Comment by TheRoyalOne2021** [comment]
the way to fix this is by typing ./ngrok http 5555 in a seperate terminal then setup nexphisher like usual with what you want and the link won't show in the nexphisher window but instead,once it's setup you click one of the ngrok links in the seperate terminal,and like a charm it takes you to the password hacking webpage you setup,and you can even use an https or http version of the link to make it more believable

**Comment by ekanep77** [comment]
How do you fix it on Mac??

**Comment by TheRoyalOne2021** [comment]
> How do you fix it on Mac??

no method will really work now with nexphisher or anything similiar i've tested,as of sometime recently phishing links for ngrok are detected and blocked outside of localhost,the only way this has any use is if the person you are phishing is on the same network

**Comment by ShakenWolf11485** [comment]
> in laptop turn on hotspot & try

it's not workigggg
