### ISSUE TITLE
Ngrok tunnel not found

### ISSUE THREAD

**Issue by PapitaRanciaUwU** [htr-tech/nexphisher#27]
When I send the link to a person, this image appears, The link does not work, what can I do?
![image](https://user-images.githubusercontent.com/69615733/90093916-4077a280-dcf2-11ea-9713-71d00eeac37c.png)

**Comment by htr-tech** [comment]
@PapitaRanciaUwU you may  have closed the terminal ?
u have to keep terminal on .. until u get the credentials
