### ISSUE TITLE
Нет ссылки ngrok 

### ISSUE THREAD

**Issue by Verxovniy** [htr-tech/nexphisher#28]
![Screenshot_20200815-060100_Termux](https://user-images.githubusercontent.com/69704715/90304096-baf41e00-debc-11ea-9d02-d193f9b6e565.jpg)

Нету ссылки которую надо сбрасывать человеку для взлома а просто пустота что делать??
Помогите пожалуйста)

**Comment by htr-tech** [comment]
@Verxovniy turn on hotspot & use ngrok option . you will get the link
