### ISSUE TITLE
Installation doesn't work on my machine 

### ISSUE THREAD

**Issue by ShayNehmad** [htr-tech/nexphisher#3]
Running on WSL Ubuntu 18.04 and ZSH as my main shell

After running `sudo setup`, I'm getting this

```sh
  _   _             _____  _     _     _
 | \ | |           |  __ \| |   (_)   | |
 |  \| | _____  __ | |__) | |__  _ ___| |__   ___ _ __
 | .   |/ _ \ \/ / |  ___/|  _ \| / __|  _ \ / _ \  __|
 | |\  |  __/>  <  | |    | | | | \__ \ | | |  __/ |
 |_| \_|\___/_/\_\ |_|    |_| |_|_|___/_| |_|\___|_| [V 1.0]

  Advanced Phishing Tool with 30+ Templates  [BY : HTR-TECH ]


 [~] Installing Packages ....

Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [932 kB]
Fetched 1184 kB in 13s (90.9 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
138 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package openssh

 [~] Setting Up Environment ....

 [~] Installation Completed !!

 [~] Type bash nexphisher to run NEXPHISHER !!
```

Also (perhaps it would be better to open up a different issue for this): an obfuscated setup script is super not cool - how do I know that it's not malicious?

**Comment by htr-tech** [comment]
> Running on WSL Ubuntu 18.04 and ZSH as my main shell
> 
> After running `sudo setup`, I'm getting this
> 
> ```shell
>   _   _             _____  _     _     _
>  | \ | |           |  __ \| |   (_)   | |
>  |  \| | _____  __ | |__) | |__  _ ___| |__   ___ _ __
>  | .   |/ _ \ \/ / |  ___/|  _ \| / __|  _ \ / _ \  __|
>  | |\  |  __/>  <  | |    | | | | \__ \ | | |  __/ |
>  |_| \_|\___/_/\_\ |_|    |_| |_|_|___/_| |_|\___|_| [V 1.0]
> 
>   Advanced Phishing Tool with 30+ Templates  [BY : HTR-TECH ]
> 
> 
>  [~] Installing Packages ....
> 
> Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
> Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
> Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
> Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
> Hit:5 https://download.docker.com/linux/ubuntu bionic InRelease
> Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [932 kB]
> Fetched 1184 kB in 13s (90.9 kB/s)
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> 138 packages can be upgraded. Run 'apt list --upgradable' to see them.
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package openssh
> 
>  [~] Setting Up Environment ....
> 
>  [~] Installation Completed !!
> 
>  [~] Type bash nexphisher to run NEXPHISHER !!
> ```
> 
> Also (perhaps it would be better to open up a different issue for this): an obfuscated setup script is super not cool - how do I know that it's not malicious?

#### @ShayNehmad  Bro Nexphisher Already Installed in your Device . 
#### Now Type `sudo bash nexphisher` to Run This Tool

**Comment by takeawish** [comment]
I am getting the same error. The package openssh cannot be located.
I am looking into this now trying to check that I am not missing anything but it does look like the package is named incorrectly in the install and is openssh-client or openssh-server depending?

**Comment by htr-tech** [comment]
> I am getting the same error. The package openssh cannot be located.
> I am looking into this now trying to check that I am not missing anything but it does look like the package is named incorrectly in the install and is openssh-client or openssh-server depending?

@takeawish Bro Nexphisher is mainly developed for Termux . In Ubuntu or Debian you can install openssh by inputting `apt-get install openssh-server`

The Required Packages are :
* php
* curl
* ssh

**Comment by Bl4omArchie** [comment]
The installation was ok for me but when I generated a phishing webpage, nothing appear. In my terminal only my IP adress pop up but that all. It's normal ?

**Comment by htr-tech** [comment]
> The installation was ok for me but when I generated a phishing webpage, nothing appear. In my terminal only my IP adress pop up but that all. It's normal ?

give Snap Shot

**Comment by ShayNehmad** [comment]
```

  _   _             _____  _     _     _
 | \ | |           |  __ \| |   (_)   | |
 |  \| | _____  __ | |__) | |__  _ ___| |__   ___ _ __
 | .   |/ _ \ \/ / |  ___/|  _ \| / __|  _ \ / _ \  __|
 | |\  |  __/>  <  | |    | | | | \__ \ | | |  __/ |
 |_| \_|\___/_/\_\ |_|    |_| |_|_|___/_| |_|\___|_| [V 1.0]

  Advanced Phishing Tool with 30+ Templates  [BY : HTR-TECH ]


 Packages are not Installed ! type bash setup

```

It is not installed, obviously.

**Comment by htr-tech** [comment]
> ```
> 
>   _   _             _____  _     _     _
>  | \ | |           |  __ \| |   (_)   | |
>  |  \| | _____  __ | |__) | |__  _ ___| |__   ___ _ __
>  | .   |/ _ \ \/ / |  ___/|  _ \| / __|  _ \ / _ \  __|
>  | |\  |  __/>  <  | |    | | | | \__ \ | | |  __/ |
>  |_| \_|\___/_/\_\ |_|    |_| |_|_|___/_| |_|\___|_| [V 1.0]
> 
>   Advanced Phishing Tool with 30+ Templates  [BY : HTR-TECH ]
> 
> 
>  Packages are not Installed ! type bash setup
> ```
> 
> It is not installed, obviously.

@ShayNehmad  bro excute
`apt-get install curl php openssh-server -y`

**Comment by htr-tech** [comment]
Installation Script Updated ! Tools Open Sourced !! 

For Termux : `bash tmux_setup`

Others : `bash setup`

**Comment by rx8driver** [comment]
tmux_setup does not complete for me. I will get you a snapshot....

**Comment by rx8driver** [comment]
Here's a screenshot bro

**Comment by rx8driver** [comment]
![photo_2020-05-10_23-58-07](https://user-images.githubusercontent.com/19867292/81522900-222c9000-931a-11ea-9940-e69cfc4497cf.jpg)

**Comment by htr-tech** [comment]
@rx8driver Bro Update & use
