### ISSUE TITLE
best

### ISSUE THREAD

**Issue by abdurahman-lab** [htr-tech/nexphisher#31]

**Comment by htr-tech** [comment]
thanks

**Comment by abdurahman-lab** [comment]
Hi bro
Bro I have problem by installing shellphish can you solve

**Comment by htr-tech** [comment]
@abdurahman-lab shellphish have been deleted

**Comment by abdurahman-lab** [comment]
Soo bro I send link to victim he say it's not working ![Screenshot_20200820-110752.png](https://user-images.githubusercontent.com/65117339/90725470-75c55700-e2d5-11ea-93de-abd791412013.png)

**Comment by abdurahman-lab** [comment]
Bro I Need urgent help

**Comment by abdurahman-lab** [comment]
Bro it worked tnxxx its awesome
