### ISSUE TITLE
Web page is not appear after sending link

### ISSUE THREAD

**Issue by shivang-1252** [htr-tech/nexphisher#37]
I sent the link to the victim when he click the link he doesn't appear web page i turn on my hospot and use ngrok  also . So pls solve this as soon as possible
.

**Comment by htr-tech** [comment]
Run This on Browser ??

Link - https://bit.ly/2PHq7ft

**Comment by shivang-1252** [comment]
I used this link but same problem appear in browser

**Comment by htr-tech** [comment]
> I used this link but same problem appear in browser

you have to keep the session alive until your job is done

**Comment by shivang-1252** [comment]
Its working thanks htr-tech😊😊
