### ISSUE TITLE
It's Not Giving Any Link

### ISSUE THREAD

**Issue by 4n0nb0y** [htr-tech/nexphisher#39]
Hi,
I am using **UBUNTU (Linux)(Downloaded From Microsoft Store)** in my **Windows10 PC**
I Had Successfully Installed Your Tool But After Completing All Procedures, It's Not Giving Me Any Link 
Kindly Help Me As Soon As Possible With That 

Thanks & Regards 
~Anonymous Boy

**Comment by htr-tech** [comment]
@4n0nb0y turn on device hotspot & try ... try installing the official image of linux os 's

**Comment by Alex-commit176** [comment]
Hello. 
I am using termux in my mobile phone. I installed your tool successfully and the link is also generating. But that link works only on my device. When I send that link to victim they said web page not available. Plss help me with this issue.

**Comment by htr-tech** [comment]
> Hello.
> I am using termux in my mobile phone. I installed your tool successfully and the link is also generating. But that link works only on my device. When I send that link to victim they said web page not available. Plss help me with this issue.

use ngrok ...

**Comment by 4n0nb0y** [comment]
> > Hello.
> > I am using termux in my mobile phone. I installed your tool successfully and the link is also generating. But that link works only on my device. When I send that link to victim they said web page not available. Plss help me with this issue.
> 
> use ngrok ... & you have to keep the termux open until your job is done



> @4n0nb0y turn on device hotspot & try ... try installing the official image of linux os 's

Hi Sir,

My PC Don't Have Hotspot and linux is already official installed 
Please help if is there any way 
Thanks

**Comment by htr-tech** [comment]
> > > Hello.
> > > I am using termux in my mobile phone. I installed your tool successfully and the link is also generating. But that link works only on my device. When I send that link to victim they said web page not available. Plss help me with this issue.
> > 
> > 
> > use ngrok ... & you have to keep the termux open until your job is done
> 
> > @4n0nb0y turn on device hotspot & try ... try installing the official image of linux os 's
> 
> Hi Sir,
> 
> My PC Don't Have Hotspot and linux is already official installed
> Please help if is there any way
> Thanks

use from this [link](https://bit.ly/2PHq7ft)

**Comment by Alex-commit176** [comment]
> > Hello.
> > I am using termux in my mobile phone. I installed your tool successfully and the link is also generating. But that link works only on my device. When I send that link to victim they said web page not available. Plss help me with this issue.
> 
> use ngrok ... & you have to keep the termux open until your job is done

No bro the link is not generating. I tried it through hotspot too. But don't know

**Comment by Alex-commit176** [comment]
No bro the link is not generating. I tried it through hotspot too. But don't know

**Comment by htr-tech** [comment]
> No bro the link is not generating. I tried it through hotspot too. But don't know

use from this [link](https://bit.ly/2PHq7ft)
