### ISSUE TITLE
Package not installed

### ISSUE THREAD

**Issue by MoonbeamMoony** [htr-tech/nexphisher#41]
Good day, sir.

I am using TermuX on Android 10. When I typed "bash nexphisher", the only thing that showed up on my screen is "package not installed. Type bash setup". I followed all of the instruction in installing Nexphisher. Did I miss anything? It also says "unable to locate package".

**Comment by htr-tech** [comment]
> Good day, sir.
> 
> I am using TermuX on Android 10. When I typed "bash nexphisher", the only thing that showed up on my screen is "package not installed. Type bash setup". I followed all of the instruction in installing Nexphisher. Did I miss anything? It also says "unable to locate package".

first type `bash tmux_setup`
then type `bash nexphisher`

turn on device hotspot & try ngrok option always

**Comment by termuxhacking11** [comment]
Ok
I will check and fix this

**Comment by MoonbeamMoony** [comment]
> > Good day, sir.
> > 
> > I am using TermuX on Android 10. When I typed "bash nexphisher", the only thing that showed up on my screen is "package not installed. Type bash setup". I followed all of the instruction in installing Nexphisher. Did I miss anything? It also says "unable to locate package".
> 
> first type `bash tmux_setup`
> then type `bash nexphisher`
> 
> turn on device hotspot & try ngrok option always
> 

Alright, I'll try. Have a nice day.

**Comment by MoonbeamMoony** [comment]
> > Good day, sir.
> > 
> > I am using TermuX on Android 10. When I typed "bash nexphisher", the only thing that showed up on my screen is "package not installed. Type bash setup". I followed all of the instruction in installing Nexphisher. Did I miss anything? It also says "unable to locate package".
> 
> first type `bash tmux_setup`
> then type `bash nexphisher`
> 
> turn on device hotspot & try ngrok option always
> 

It's working! Thank you so much for helping me! Have a great day!
