### ISSUE TITLE
csrftoken

### ISSUE THREAD

**Issue by Prhm021** [htr-tech/nexphisher#42]
Hi bro
When I want use this give me this error "csrftoken"🤕
Plz help meeeee🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by htr-tech** [comment]
give screenshot

**Comment by Prhm021** [comment]
Thanks for answer me
I have this problem in many github for ex. instahack
![20200928_114513.jpg](https://user-images.githubusercontent.com/65857796/94407411-44fff980-0180-11eb-9ac3-5fc08aa099bf.jpg)
Plz help me🙏🏻❤

**Comment by htr-tech** [comment]
@Prhm021 thats not zphisher then why you have created issue here .. try asking the author
