### ISSUE TITLE
How do i start nexphisher for the second time.

### ISSUE THREAD

**Issue by brayanasf** [htr-tech/nexphisher#52]
I installed nexphisher on turmux and used it and it worked perfectly fine. But then i closed turmux. And when i opened turmux again qnd used
 
"bash nexphisher" 

code to run the program it says

nexphisher: Is a directory

How do i open nexphisher for the second time ?

![20201112_065829.jpg](https://user-images.githubusercontent.com/74333976/98883641-850f0780-24b4-11eb-9503-95adb18b9e74.jpg)

**Comment by htr-tech** [comment]
@brayanasf 

`cd nexphisher`
`bash nexphisher`

**Comment by brayanasf** [comment]
Thanks man. Im guessing that was a stupid question. 😂
Thanks anyways. Im new
