### ISSUE TITLE
Page Not Found When Opening Link

### ISSUE THREAD

**Issue by Essentialistic** [htr-tech/nexphisher#53]
I enter the ngrok link and it pops up saying "Not Found"

**Comment by htr-tech** [comment]
@Essentialistic you have to keep your termux /terminal session alive

**Comment by Zheekkheed** [comment]
i tried shortening my localhost link but its not working and when i try accessing the localhost link on my browser it doesn't load the phished page

**Comment by htr-tech** [comment]
@Zheekkheed use ngrok
