### ISSUE TITLE
i dont get a link - it says show link to victim but thers no link, nothing 

### ISSUE THREAD

**Issue by matykubon** [htr-tech/nexphisher#54]

**Comment by matykubon** [comment]
[~] Send the link to victim :                          
 [~] Waiting for Login Info, Ctrl + C to exit.

**Comment by htr-tech** [comment]
@matykubon turn on hotspot & try ngrok

**Comment by nesith2002** [comment]
same prob! 
no victims link 
why is that? i past the ngrok link also

**Comment by matykubon** [comment]
I eventually figured it out. I don't know if u are using kali or something
else but I was using termux on android. U need to setup ngrok (get ur auth.
token and all dat first). If you look up videos on just ngrok, you should
be fine since its pretty straight forward. (Just install it and get a
verification token) After that, you just run your phishing program like you
would. Sometimes, some of them just don't work but often its because of
ngrok. Also turn on your data and hotspot. I don't know how hotspot helps
but it says so in most 'help' files.

Dne ne 6. 12. 2020 5:33 uživatel nesith2002 <notifications@github.com>
napsal:

**Comment by htr-tech** [comment]
@matykubon you can work without the ngrok token also 😄
