### ISSUE TITLE
ua-563b05a2.localhost.run tunneled with tls termination

### ISSUE THREAD

**Issue by suriano998** [htr-tech/nexphisher#58]
After Starting A Server With Nexphisher i get this:  ua-563b05a2.localhost.run tunneled with tls termination

and no link.
pls help.

**Comment by htr-tech** [comment]
@suriano998 turn on hptspot & use ngrok .. localhost.run is buggy 😢

**Comment by suriano998** [comment]
> @suriano998 turn on hptspot & use ngrok .. localhost.run is buggy 😢

i dont have an hotspot

**Comment by htr-tech** [comment]
@suriano998 then use zphisher ( ngrok patched )

https://github.com/htr-tech/zphisher
