### ISSUE TITLE
Ngrock tunnel expired

### ISSUE THREAD

**Issue by VedK-droid** [htr-tech/nexphisher#59]
Bro ngrock tunnel is expired plz fix it

**Comment by htr-tech** [comment]
@VedK-droid ngrok link is valid for 1 hours only 😢

**Comment by VedK-droid** [comment]
Naaah its down

**Comment by VedK-droid** [comment]
Try it

**Comment by htr-tech** [comment]
@VedK-droid really dude ? 
![image](https://user-images.githubusercontent.com/56682134/104301307-b0809380-54f1-11eb-9ea4-ba72ba2d1749.png)

**Comment by VedK-droid** [comment]
Oh think it works now sorry dude

**Comment by VedK-droid** [comment]
Can I get your email so I can chat personal

**Comment by htr-tech** [comment]
> Can I get your email so I can chat personal

knock me on my fb : https://fb.com/tahmid.rayat.official

**Comment by VedK-droid** [comment]
Sorry I don't have fb but Can you WhatsApp me at this no. +1 (475) 263-8156 please need to talk something important 🙏 🙌
