### ISSUE TITLE
LocalHost doesn't work - Empty Link

### ISSUE THREAD

**Issue by tofylion** [htr-tech/nexphisher#63]
I've tried setting up ngrok eith termux and it wokred successfully, but the link can't be customized. Localhost doesn't work for me and generates an empty link. Am I missing something or is it an issue?

**Comment by VedK-droid** [comment]
You need hotpot on

**Comment by tofylion** [comment]
> You need hotspot on

I've tried that. Unfortunately, it still doesn't work

**Comment by VedK-droid** [comment]
Br0 sorry to inform nexphisher no longer works😢

**Comment by tofylion** [comment]
> Br0 sorry to inform nexphisher no longer works😢

No, it still works with Ngrok and LocalHostRun

**Comment by htr-tech** [comment]
@tofylion localhost is just for manual port  forwarding ... u can use ngrok 😸

**Comment by Cenzoizhacker** [comment]
> @tofylion localhost is just for manual port  forwarding ... u can use ngrok 😸 

Ngrok it's not working do I have to use mobile data or?
