### ISSUE TITLE
please add a Mask Url

### ISSUE THREAD

**Issue by bmaster15** [htr-tech/nexphisher#67]
niceee tool plss add a maskurl plsss

**Comment by jaykali** [comment]
try [MaskPhish](https://github.com/jaykali/maskphish)

**Comment by bmaster15** [comment]
Still Not working in maskphish

**Comment by htr-tech** [comment]
@bmaster15 bro use [Zphisher](https://github.com/htr-tech/zphisher) I am currently focusing on that tool
