### ISSUE TITLE
No link

### ISSUE THREAD

**Issue by PatriRGB** [htr-tech/nexphisher#68]
![Screenshot_2021-01-05-20-06-36-262_com termux](https://user-images.githubusercontent.com/76879237/103688928-dc03fb00-4f92-11eb-961e-a7d72776fc2c.jpg)
No link :(

**Comment by htr-tech** [comment]
@PatriRGB turn on hotspot & try again

**Comment by chrisfal10** [comment]
In the directory of nexphisher 
Type 
`cd .htr `

`rm -r -f ngrok`

Then make sure you have wget and unzip (apt install wget unzip)

Then 

`wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip`

`unzip  ngrok-stable-linux-arm.zip`

`chmod +x ngrok`

After this make sure u get ur token from ngrok

And Type  

`./ngrok authtoken `YOUR_AUTH_TOKEN_HERE`

And done run the command it should work

**Comment by htr-tech** [comment]
> In the directory of nexphisher
> Type
> `cd .htr `
> 
> `rm -r -f ngrok`
> 
> Then make sure you have wget and unzip (apt install wget unzip)
> 
> Then
> 
> `wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip`
> 
> `unzip ngrok-stable-linux-arm.zip`
> 
> `chmod +x ngrok`
> 
> After this make sure u get ur token from ngrok
> 
> And Type
> 
> `./ngrok authtoken `YOUR_AUTH_TOKEN_HERE`
> 
> And done run the command it should work

💘
