### ISSUE TITLE
Sorry I don't have fb but Can you WhatsApp me at this no. +1 (475) 263-8156 please need to talk something important 🙏 🙌

### ISSUE THREAD

**Issue by VedK-droid** [htr-tech/nexphisher#69]
_Originally posted by @VedK-droid in https://github.com/htr-tech/nexphisher/issues/59#issuecomment-758688508_

**Comment by htr-tech** [comment]
@VedK-droid I dont have whatsapp 😩

**Comment by VedK-droid** [comment]
> @VedK-droid I dont have whatsapp 😩 

Do you have discord or else email me at 
vkomrelliwar@gmail.com

**Comment by htr-tech** [comment]
@VedK-droid me on discord `ItzCatHere#4180`
