### ISSUE TITLE
Tmux_setup doesn't work

### ISSUE THREAD

**Issue by abudoy687** [htr-tech/nexphisher#7]
$ bash tmux_setup                                       tmux_setup: line 2: $'\r': command not found            tmux_setup: line 3: syntax error near unexpected token `$'{\r''
'mux_setup: line 3: `banner() {

**Comment by abudoy687** [comment]
_   _             _____  _     _     _                 | \ | |           |  __ \| |   (_)   | |                |  \| | _____  __ | |__) | |__  _ ___| |__   ___ _ __   | .   |/ _ \ \/ / |  ___/|  _ \| / __|  _ \ / _ \  __|  | |\  |  __/>  <  | |    | | | | \__ \ | | |  __/ |     |_| \_|\___/_/\_\ |_|    |_| |_|_|___/_| |_|\___|_| [V 1.0]                                                                                                              Advanced Phishing Tool with 30+ Templates  [BY : HTR-TECH ]                                                                                                                                                                    Packages are not Installed ! type bash setup                                                                   $ bash tmux_setup                                       tmux_setup: line 2: $'\r': command not found            tmux_setup: line 3: syntax error near unexpected token `$'{\r''
'mux_setup: line 3: `banner() {

**Comment by abudoy687** [comment]
> $ bash tmux_setup                                       

> tmux_setup:` line 2: $'\r': command not found            

> tmux_setup: line 3: syntax error near unexpected token `$'{\r''

> 'mux_setup:` line 3: `banner() {

**Comment by htr-tech** [comment]
bug fixed . Re-install or type `git pull origin` inside nexphisher repo
