### ISSUE TITLE
Add messenger and tiktok

### ISSUE THREAD

**Issue by sanushafernando** [htr-tech/nexphisher#71]
please add messenger and tiktok

**Comment by htr-tech** [comment]
@sanushafernando ok .. i will try

**Comment by htr-tech** [comment]
@sanushafernando use https://github.com/htr-tech/zphisher

i have added messenger and tiktok in that 😄

**Comment by sanushafernando** [comment]
Thx brother😜

**Comment by htr-tech** [comment]
@sanushafernando you are most welcome 😄
