### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by walid1010** [htr-tech/nexphisher#75]
![Screenshot_20210129-150037_Termux](https://user-images.githubusercontent.com/78182176/106283922-ce186180-6242-11eb-8f9c-a13013a0e196.jpg)
I tried also with hotspot and still the same:( please help

**Comment by htr-tech** [comment]
@walid1010 turn on device hotspot & try ngrok again 😕

**Comment by walid1010** [comment]
That's what I did...I think I don't have ngrok installed maybe...!? How to install it if that's the case? Thank you

**Comment by htr-tech** [comment]
> That's what I did...I think I don't have ngrok installed maybe...!? How to install it if that's the case? Thank you

run the setup file .. bash tmux_setup

**Comment by dima20003** [comment]
I have this problem too with and without hotspot. Who can help me please 🥺😭😭. Thanks for this repository
😅👍👍👍👍👍👍👍

**Comment by chrisfal10** [comment]
Try this it doesn't require Hotspot 
It is a problem with the ngrok package this should work
In the directory of nexphisher 
Type 
`cd .htr `

`rm -r -f ngrok`

Then make sure you have wget and unzip (apt install wget unzip)

Then 

`wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip`

`unzip  ngrok-stable-linux-arm.zip`

`chmod +x ngrok`

After this make sure u get ur token from ngrok

And Type  

`./ngrok authtoken `YOUR_AUTH_TOKEN_HERE`

And done run the command it should work
It's should look like this then 
![Screenshot_20210511-222756_Termux](https://user-images.githubusercontent.com/79748717/117856467-444c4b80-b2a9-11eb-87dd-d139846a3f8d.jpg)

**Comment by htr-tech** [comment]
> Try this it doesn't require Hotspot
> It is a problem with the ngrok package this should work
> In the directory of nexphisher
> Type
> `cd .htr `
> 
> `rm -r -f ngrok`
> 
> Then make sure you have wget and unzip (apt install wget unzip)
> 
> Then
> 
> `wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip`
> 
> `unzip ngrok-stable-linux-arm.zip`
> 
> `chmod +x ngrok`
> 
> After this make sure u get ur token from ngrok
> 
> And Type
> 
> `./ngrok authtoken `YOUR_AUTH_TOKEN_HERE`
> 
> And done run the command it should work
> It's should look like this then
> ![Screenshot_20210511-222756_Termux](https://user-images.githubusercontent.com/79748717/117856467-444c4b80-b2a9-11eb-87dd-d139846a3f8d.jpg)

💘 {3} 😄
