### ISSUE TITLE
Link not generating 

### ISSUE THREAD

**Issue by jokeronearth** [htr-tech/nexphisher#77]
Nexphisher Tool installed successfully but link is not generating . please help me anyone

**Comment by htr-tech** [comment]
@jokeronearth turn on hotspot & try again 🌚

**Comment by jokeronearth** [comment]
ok Bro. i will try Again with Hotspot

**Comment by SecurDrgorP** [comment]
But the hotspot work on my browser but when I sent the link in WhatsApp like , it didn't work in another device

**Comment by htr-tech** [comment]
> But the hotspot work on my browser but when I sent the link in WhatsApp like , it didn't work in another device

use ngrok links

**Comment by SecurDrgorP** [comment]
yeah , but how?, i installed it and do it unzip on termux... but how can i make it work !?

**Comment by htr-tech** [comment]
> yeah , but how?, i installed it and do it unzip on termux... but how can i make it work !?

sometimes that doesn't work on some devices .. i have made e short solution .. better check it & tell me if you have any problem

https://drive.google.com/file/d/1nkhpj8MKRTqQbK1v3OuUJtaxcRdEp-M4/view?usp=sharing

**Comment by SecurDrgorP** [comment]
alright thanks bro
