### ISSUE TITLE
not finding dependences

### ISSUE THREAD

**Issue by JefferssonVMT** [htr-tech/nexphisher#79]
not finding packages like openssl

**Comment by htr-tech** [comment]
😕 nexphisher requires wget git curl php openssh

**Comment by JefferssonVMT** [comment]
then?
what can we do?

we have 2 dependences that termux is not installing

**Comment by htr-tech** [comment]
> then?
> what can we do?
> 
> we have 2 dependences that termux is not installing

`apt install wget git curl php openssh -y`

**Comment by JefferssonVMT** [comment]
Nice, is installed now

Buuut ngrok phishing link is always empty

**Comment by htr-tech** [comment]
> Nice, is installed now
> 
> Buuut ngrok phishing link is always empty

turn on hotspot & try again
