### ISSUE TITLE
Page not found on my victims side

### ISSUE THREAD

**Issue by xenonxander** [htr-tech/nexphisher#86]
Before i send the link i try it first. To me it's working. Login page was there. But when i send it to my victim page not found. Can someone help me what to do? 
![received_1089031628237667](https://user-images.githubusercontent.com/76180175/111061982-95191100-84bf-11eb-92ed-90982fd1b2c1.jpeg)

**Comment by himanshu0789** [comment]
Make sure you and your victim use the same server



Just example if you using mobile data and your victim use Wi-Fi that time
nexphisher not work good so make sure if you useing mobile data and your
victim also use mobile data

**Comment by htr-tech** [comment]
@xenonxander generate ngrok link & share it to victim .. 
**Note: you have to keep your termux/terminal session alive**

**Comment by wlmzz** [comment]
Try first 
- [$] apt install ngrok-client
- [$] ./ngrok

**Comment by xenonxander** [comment]
> @xenonxander generate ngrok link & share it to victim ..
> **Note: you have to keep your termux/terminal session alive**

Yes I'm using the ngrok link. But it's same. Before I'm using it very well. But now i encountered that problem. Thank you all

**Comment by htr-tech** [comment]
> > @xenonxander generate ngrok link & share it to victim ..
> > **Note: you have to keep your termux/terminal session alive**
> 
> Yes I'm using the ngrok link. But it's same. Before I'm using it very well. But now i encountered that problem. Thank you all

 you have to keep your termux/terminal session alive 😐

**Comment by Ajay-singh1** [comment]
I have an issue.The issue is tunelling ngrok.io not found after the victim had entered the form filling.Is tge link permanent or temporary.
I'll be glad if you help me with this issue.

**Comment by htr-tech** [comment]
@Ajay-singh1 link is valid for maximum 2 hours 😐 [without token]

& you have to keep  your terminal session alive

**Comment by xenonxander** [comment]
> @Ajay-singh1 link is valid for maximum 2 hours 😐 [without token]
> 
> & you have to keep your terminal session alive

Yes sir. We know that. Even i tried to make a new link using NGrok. After i send it to victim. When they click it the page not found 🤔

**Comment by xenonxander** [comment]
Is it posible that Facebook know what i am doing? Because after i send the link to the victim so many ip address is logging in termux. And if i locate their ip its in different countries. Most os United States

**Comment by htr-tech** [comment]
@xenonxander send one link to maximum one people... otherwise the tunnel will be broken 🤔

**Comment by xenonxander** [comment]
> > > @xenonxander generate ngrok link & share it to victim ..
> > > **Note: you have to keep your termux/terminal session alive**
> > 
> > 
> > Yes I'm using the ngrok link. But it's same. Before I'm using it very well. But now i encountered that problem. Thank you all
> 
> you have to keep your termux/terminal session alive 😐

Yes. I didn't close it. When i open the link it's working to me. I see my ip amin the log and my credentials also. But to my victim. Always page not found

**Comment by htr-tech** [comment]
> > > > @xenonxander generate ngrok link & share it to victim ..
> > > > **Note: you have to keep your termux/terminal session alive**
> > > 
> > > 
> > > Yes I'm using the ngrok link. But it's same. Before I'm using it very well. But now i encountered that problem. Thank you all
> > 
> > 
> > you have to keep your termux/terminal session alive 😐
> 
> Yes. I didn't close it. When i open the link it's working to me. I see my ip amin the log and my credentials also. But to my victim. Always page not found

maybe there is a problem with victims browser 🤔 tell him to chane his browser & try ..  🤔🤔

**Comment by htr-tech** [comment]
#87

**Comment by Exodus0228** [comment]
> Is it posible that Facebook know what i am doing? Because after i send the link to the victim so many ip address is logging in termux. And if i locate their ip its in different countries. Most os United States 

Same here any solution 
Masters ?
