### ISSUE TITLE
Where is the Credit Author ? (HIDDENEYE COPIED)

### ISSUE THREAD

**Issue by An0nUD4Y** [htr-tech/nexphisher#9]
All the pages And Tactics Looks Similar To my Tool [Hiddeneye](https://github.com/darksecdevelopers/hiddeneye)
Stop Being a Noob And Give the Credits To All developers.

**Comment by shadowlabx** [comment]
> All the pages And Tactics Looks Similar To my Tool [Hiddeneye](https://github.com/darksecdevelopers/hiddeneye)
> Stop Being a Noob And Give the Credits To All developers.
> 

This guys just ripping tools of others and isn't adding credits. Look in closed issues I mentioned it and he added it claiming he had added it 😂

**Comment by htr-tech** [comment]
@An0nUD4Y I was Updating The Readme. Look Carefully

**Comment by An0nUD4Y** [comment]
@htr-tech , Really...
Please be responsible...  People helps open source by contributing just to let everyone learn new things. And if something is open-sourced doesn't meet you will not credit the developers. Thelinuxchoice also said same.. 
Try improving and helping to the original tools.
