### ISSUE TITLE
send the victim this link

### ISSUE THREAD

**Issue by trick007-cyber** [htr-tech/nexphisher#93]
hey guys i got problem, the black eye said send the victim this link: however the link is empty.
what should i do? here's the preview

[*] Starting php server...
[*] Starting ngrok server...
[*] Send this link to the Victim:  <-- (no link)
[*] Waiting victim open the link ...

**Comment by htr-tech** [comment]
if you are in termux excute the following commands

`apt install proot resolv-conf -y`
`termux-chroot bash nexphisher`

**Comment by trick007-cyber** [comment]
thanks for the reply, however in this moment im optimization my laptop. any
clue??

**Comment by Martin8mv** [comment]
same problem and above commands doesn't work
