### ISSUE TITLE
Cant access localhost !

### ISSUE THREAD

**Issue by blaze-Youssef** [htr-tech/nexphisher#95]
Hello, I have a problem when choosing the localhost option for hosting, I can't acces the page from outside the device (local network), I noticed that it displays listening on 127.0.0.1, Wich after I google it, I realized that it listens only only for the local machine connections.
Any help I'll be thankful 😊.

**Comment by blaze-Youssef** [comment]
Well, After searching I found a way how to solve it! But the next problem is how to chanhe port! 
I think it's important to add this option !

**Comment by chrisfal10** [comment]
Take try this

**Comment by htr-tech** [comment]
yeah 

> In the directory of nexphisher
> Type
> `cd .htr `
> 
> `rm -r -f ngrok`
> 
> Then make sure you have wget and unzip (apt install wget unzip)
> 
> Then
> 
> `wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip`
> 
> `unzip ngrok-stable-linux-arm.zip`
> 
> `chmod +x ngrok`
> 
> After this make sure u get ur token from ngrok
> 
> And Type
> 
> `./ngrok authtoken `YOUR_AUTH_TOKEN_HERE`
> 
> And done run the command it should work

💘
