### ISSUE TITLE
Cannot reach website

### ISSUE THREAD

**Issue by RATUL099** [htr-tech/nexphisher#97]
> when I send link to the victim and he trys to get to the website but the website don't come it shows this website cannot be reached. And the link not generating any other host accept local host. Plz fix this problem bro

**Comment by htr-tech** [comment]
> > when I send link to the victim and he trys to get to the website but the website don't come it shows this website cannot be reached. And the link not generating any other host accept local host. Plz fix this problem bro

if you are using termux then turn on hotspot & try with ngrok

keep your terminal open until your job is done

**Comment by mohit67476116** [comment]
Bro i had try all this but it can`t work

**Comment by RATUL099** [comment]
Thanks bro
